
<?php
/**
 * Route table. Generated by `/www/wwwroot/dev.occulta.net/generator.php` at 2020-04-04 20:24:03.
 * YOU DON'T HAVE TO MODIFY THIS FILE, JUST GENERATE IT :)
 */

$apiAppApiArticle = new \App\Api\Article();
Flight::route('POST /api/admin/article', array($apiAppApiArticle, 'write'));
Flight::route('PUT /api/admin/article/@id', array($apiAppApiArticle, 'update'));
Flight::route('DELETE /api/admin/article/@id', array($apiAppApiArticle, 'remove'));
Flight::route('GET /api/admin/article/list', array($apiAppApiArticle, 'list'));
Flight::route('GET /api/admin/article/@id', array($apiAppApiArticle, 'get'));
Flight::route('PUT /api/admin/article/@id/status', array($apiAppApiArticle, 'setStatus'));

$apiAppApiAuth = new \App\Api\Auth();
Flight::route('POST /api/auth/login', array($apiAppApiAuth, 'login'));
Flight::route('POST /api/auth/logout', array($apiAppApiAuth, 'logout'));
Flight::route('GET /api/auth.info', array($apiAppApiAuth, 'getInfo'));

$apiAppApiCollection = new \App\Api\Collection();

$apiAppApiContent = new \App\Api\Content();
Flight::route('POST /api/content/', array($apiAppApiContent, 'index'));

$apiAppApiField = new \App\Api\Field();
Flight::route('POST /api/admin/field/meta', array($apiAppApiField, 'addMeta'));
Flight::route('GET /api/admin/field/meta/list/@name', array($apiAppApiField, 'listMeta'));
Flight::route('PUT /api/admin/field/meta/@id', array($apiAppApiField, 'updateMeta'));
Flight::route('DELETE /api/admin/field/meta/@id', array($apiAppApiField, 'removeMeta'));
Flight::route('GET /api/admin/content/@id/field', array($apiAppApiField, 'getProperties'));
Flight::route('POST /api/admin/content/@id/field', array($apiAppApiField, 'setProperties'));

$apiAppApiHome = new \App\Api\Home();
Flight::route('GET /api', array($apiAppApiHome, 'index'));

$apiAppApiPage = new \App\Api\Page();
Flight::route('POST /api/admin/page', array($apiAppApiPage, 'write'));
Flight::route('PUT /api/admin/page/@id', array($apiAppApiPage, 'update'));
Flight::route('DELETE /api/admin/page/@id', array($apiAppApiPage, 'remove'));
Flight::route('GET /api/admin/page/list', array($apiAppApiPage, 'list'));
Flight::route('GET /api/admin/page/@id', array($apiAppApiPage, 'get'));

$apiAppViewArticle = new \App\View\Article();
Flight::route('GET /archive/@uuid', array($apiAppViewArticle, 'index'));

$apiAppViewHome = new \App\View\Home();
Flight::route('GET /', array($apiAppViewHome, 'index'));
Flight::route('GET /page/@page', array($apiAppViewHome, 'page'));
Flight::route('GET /search', array($apiAppViewHome, 'search'));
Flight::route('GET /search/page/@page', array($apiAppViewHome, 'searchPage'));

$apiAppViewPage = new \App\View\Page();
Flight::route('GET /@slug:.*\.html', array($apiAppViewPage, 'index'));

$apiAppViewResource = new \App\View\Resource();
Flight::route('GET /assets/*', array($apiAppViewResource, 'index'));

$apiAppViewAdminArticle = new \App\View\Admin\Article();
Flight::route('GET /admin/article/write(/@id)', array($apiAppViewAdminArticle, 'write'));
Flight::route('GET /admin/article/manage', array($apiAppViewAdminArticle, 'manage'));
Flight::route('GET /admin/article/manage/page/@page', array($apiAppViewAdminArticle, 'managePage'));

$apiAppViewAdminAuth = new \App\View\Admin\Auth();
Flight::route('GET /admin/login', array($apiAppViewAdminAuth, 'login'));
Flight::route('POST /admin/login', array($apiAppViewAdminAuth, '_login'));

$apiAppViewAdminCollection = new \App\View\Admin\Collection();
Flight::route('GET /admin/collection/manage', array($apiAppViewAdminCollection, 'manage'));

$apiAppViewAdminField = new \App\View\Admin\Field();
Flight::route('GET /admin/field/manage', array($apiAppViewAdminField, 'manage'));

$apiAppViewAdminHome = new \App\View\Admin\Home();
Flight::route('GET /admin(/@page)', array($apiAppViewAdminHome, 'index'));

$apiAppViewAdminPage = new \App\View\Admin\Page();
Flight::route('GET /admin/page/write(/@id)', array($apiAppViewAdminPage, 'write'));
Flight::route('GET /admin/page/manage', array($apiAppViewAdminPage, 'manage'));
Flight::route('GET /admin/page/manage/page/@page', array($apiAppViewAdminPage, 'managePage'));

$apiAppViewAdminTheme = new \App\View\Admin\Theme();
Flight::route('GET /admin/theme/manage', array($apiAppViewAdminTheme, 'manage'));

